version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - ./docker/database:/var/lib/mysql
  app:
    container_name: app
    build: .
    volumes:
      - .:/sample_app
    ports:
      - "3001:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: 12345678
    depends_on:
      - db
