validates:
  maximum_name: 50
  maximum_email: 255
  minimum_pass: 6
helper:
  size: 80
controller:
  remember_me: "1"
  per_page: 20
users:
  size: 50
  time: 2
microposts:
  maximum_content: 140
  size: 50
  size_picture: 5
avatar:
  size: 50
picture_uploader:
  height_picture: 400
  wight_picture: 400
